// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Web.Data.Models
{
    [Table("Article_TagCloud_Mapping")]
    public partial class ArticleTagCloudMapping
    {
        [Key]
        public Guid ArticleId { get; set; }
        [Key]
        public Guid TagId { get; set; }

        [ForeignKey(nameof(ArticleId))]
        [InverseProperty("ArticleTagCloudMapping")]
        public virtual Article Article { get; set; }
        [ForeignKey(nameof(TagId))]
        [InverseProperty(nameof(TagCloud.ArticleTagCloudMapping))]
        public virtual TagCloud Tag { get; set; }
    }
}