// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Web.Data.Models
{
    public partial class Article
    {
        public Article()
        {
            ArticleTagCloudMapping = new HashSet<ArticleTagCloudMapping>();
        }

        [Key]
        [Column("ID")]
        public Guid Id { get; set; }
        [Required]
        [StringLength(100)]
        public string Title { get; set; }
        [Required]
        public string Body { get; set; }
        [Required]
        [StringLength(250)]
        public string CoverPhoto { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreateDate { get; set; }

        [InverseProperty("Article")]
        public virtual ICollection<ArticleTagCloudMapping> ArticleTagCloudMapping { get; set; }
    }
}